/*
 * To change this template, choose Tools | Templates and open the template in
 * the editor.
 */
package vista.wizard;

import controladores.ControladorCliente;
import controladores.MetodosGenerales;
import java.util.List;
import javax.swing.JOptionPane;
import modelos.Cliente;
import modelos.Hotel;

/**
 *
 * @author Pc
 */
public class WizardHotel extends javax.swing.JFrame {

    /**
     * Creates new form WizardCreacion
     */
    public WizardHotel() {
        initComponents();
        setLocationRelativeTo(null);
        this.setTitle("Informacion del hotel");
        btnSugerencias.grabFocus();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        Terminos = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        terminosDeUso = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        chkAcepto = new javax.swing.JCheckBox();
        btnFinalizar = new javax.swing.JButton();
        txtNombreHotel = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbxNombresHotel = new javax.swing.JComboBox();
        txtUrl = new javax.swing.JTextField();
        cbxUrlsHotel = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnSiguiente = new javax.swing.JButton();
        btnSugerencias = new javax.swing.JButton();

        terminosDeUso.setColumns(20);
        terminosDeUso.setRows(5);
        terminosDeUso.setText("HOSTAL SYSTEM V3 ON WINDOWS OPERATING SYSTEM \n\n\nMicrosoft Corporation (or based on where you live, one of its affiliates) \nlicenses this supplement to you.  If you are licensed to use \nMicrosoft Windows operating system software (for which this supplement is applicable) \n(the “software”), you may use this supplement.  \nYou may not use it if you do not have a license for the software.  \nYou may use a copy of this supplement with each validly licensed copy of the software.\nThe following license terms describe additional use terms for this supplement.  \nThese terms and the license terms for the software apply to your use of the supplement.  \nIf there is a conflict, these supplemental license terms apply.\nBY USING THIS SUPPLEMENT, YOU ACCEPT THESE TERMS.  \nIF YOU DO NOT ACCEPT THEM, DO NOT USE THIS SUPPLEMENT.\nIf you comply with these license terms, you have the rights below.\n1.\tSUPPORT SERVICES FOR SUPPLEMENT.  Microsoft provides support services for this \nsoftware as described at www.support.microsoft.com/common/international.aspx.\n2.   MICROSOFT .NET BENCHMARK TESTING. The software includes the .NET Framework, \nWindows Communication Foundation, Windows Presentation Foundation, \nand Windows Workflow Foundation components of the Windows operating systems (.NET Components).  \nYou may conduct internal benchmark testing of the .NET Components. You may disclose the results \nof any benchmark test of the .NET Components, provided that you comply with the conditions \nset forth at http://go.microsoft.com/fwlink/?LinkID=66406.\n\nNotwithstanding any other agreement you may have with Microsoft, if you disclose such benchmark \ntest results, Microsoft shall have the right to disclose the results of benchmark tests it conducts\n of your products that compete with the applicable .NET Component, provided it complies with the \nsame conditions set forth at http://go.microsoft.com/fwlink/?LinkID=66406.\n");
        terminosDeUso.setEditable(false);
        jScrollPane1.setViewportView(terminosDeUso);

        jLabel7.setText("Terminos de uso y licencias de usuario del sistema HOTEL SYSTEM V.2");

        chkAcepto.setText("He leido y acepto los terminos de uso");
        chkAcepto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAceptoActionPerformed(evt);
            }
        });

        btnFinalizar.setText("Finalizar");
        btnFinalizar.setEnabled(false);
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TerminosLayout = new javax.swing.GroupLayout(Terminos.getContentPane());
        Terminos.getContentPane().setLayout(TerminosLayout);
        TerminosLayout.setHorizontalGroup(
            TerminosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TerminosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TerminosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(TerminosLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 132, Short.MAX_VALUE))
                    .addGroup(TerminosLayout.createSequentialGroup()
                        .addComponent(chkAcepto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFinalizar)))
                .addContainerGap())
        );
        TerminosLayout.setVerticalGroup(
            TerminosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TerminosLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(TerminosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TerminosLayout.createSequentialGroup()
                        .addComponent(chkAcepto)
                        .addGap(0, 21, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TerminosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnFinalizar)))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, cbxNombresHotel, org.jdesktop.beansbinding.ELProperty.create("${selectedItem}"), txtNombreHotel, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        txtNombreHotel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNombreHotelMousePressed(evt);
            }
        });

        jLabel1.setText("Nombre de Hotel");

        jLabel2.setText("Escoje una dirección web para el hotel");

        cbxNombresHotel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ingrese un nombre para el Hotel" }));
        cbxNombresHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxNombresHotelActionPerformed(evt);
            }
        });

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, cbxUrlsHotel, org.jdesktop.beansbinding.ELProperty.create("${selectedItem}"), txtUrl, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        txtUrl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtUrlMousePressed(evt);
            }
        });

        cbxUrlsHotel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Escoja un URL" }));
        cbxUrlsHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxUrlsHotelActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 11));
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("escojala con mucho cuidado debido a que ya no podrá ser cambiada.");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel4.setText(".clerk.im");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel5.setText("Información del Hotel");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel6.setText("http://");

        btnSiguiente.setText("Siguiente >");
        btnSiguiente.setEnabled(false);
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        btnSugerencias.setText("Sugerencias");
        btnSugerencias.setEnabled(false);
        btnSugerencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSugerenciasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtUrl))
                            .addComponent(txtNombreHotel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxNombresHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbxUrlsHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSugerencias)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSiguiente))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreHotel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxNombresHotel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSugerencias)
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxUrlsHotel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(4, 4, 4)
                .addComponent(btnSiguiente)
                .addGap(14, 14, 14))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSugerenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSugerenciasActionPerformed
        if (ControladorCliente.esNulos(txtNombreHotel.getText())) {
            JOptionPane.showMessageDialog(this, "Ingrese el nombre del hotel", "Error ingreso de Datos", 2);
        } else {
            List<String> opcionesNombreHotel = ControladorCliente.opcionesNombreHotel(txtNombreHotel.getText());
            cbxNombresHotel.setModel(new javax.swing.DefaultComboBoxModel(ControladorCliente.listaString(opcionesNombreHotel)));
            cbxNombresHotel.setSelectedIndex(-1);

        }

    }//GEN-LAST:event_btnSugerenciasActionPerformed

    private void txtNombreHotelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreHotelMousePressed
        if (txtNombreHotel.getText().equals("Ingrese un nombre para el Hotel")) {
            txtNombreHotel.setText("");
            btnSugerencias.setEnabled(true);
        }
    }//GEN-LAST:event_txtNombreHotelMousePressed

    private void txtUrlMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUrlMousePressed
        // Escoja un URL
        if (txtUrl.getText().equals("Escoja un URL")) {
            txtUrl.setText("");

        }
    }//GEN-LAST:event_txtUrlMousePressed

    private void cbxUrlsHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxUrlsHotelActionPerformed
        if (cbxUrlsHotel.getSelectedIndex() != -1) {
            btnSiguiente.setEnabled(true);
        }
    }//GEN-LAST:event_cbxUrlsHotelActionPerformed

    private void cbxNombresHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxNombresHotelActionPerformed
        if (cbxNombresHotel.getSelectedIndex() != -1) {
            List<String> opcionesUrlHotel = ControladorCliente.opcionesUrlHotel(txtNombreHotel.getText());
            cbxUrlsHotel.setModel(new javax.swing.DefaultComboBoxModel(ControladorCliente.listaString(opcionesUrlHotel)));
            cbxUrlsHotel.setSelectedIndex(-1);
            // txtNombreHotel.setEditable(false);
            txtUrl.setEditable(false);
        }
    }//GEN-LAST:event_cbxNombresHotelActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        Cliente cliente = null;
        Hotel hotel = null;
        if (MetodosGenerales.clienteGlobal != null ) {
            if(!ControladorCliente.esNulos(txtNombreHotel.getText())){
            cliente = MetodosGenerales.clienteGlobal;
            hotel = new Hotel(txtNombreHotel.getText(),txtUrl.getText());
            MetodosGenerales.clienteGlobal = cliente;
            MetodosGenerales.hotelGlobal = hotel;
            Terminos.setSize(600,400);
            Terminos.setLocationRelativeTo(null);
            Terminos.setVisible(true);
            this.dispose();
            }else{
                JOptionPane.showMessageDialog(this, "Ingrese un nombre para el Hotel", "Error interno", 2);
            }
        } else {
            JOptionPane.showMessageDialog(this, "No existe un cliente creado", "Error interno", 2);
            
        }
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void chkAceptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAceptoActionPerformed
        if(chkAcepto.isSelected()){
            btnFinalizar.setEnabled(true);
        }
    }//GEN-LAST:event_chkAceptoActionPerformed

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        System.out.println("Creando las habitaciones...");
        System.out.println(MetodosGenerales.clienteGlobal.getNombreCliente());
        System.out.println(MetodosGenerales.clienteGlobal.getClave());
        System.out.println(MetodosGenerales.clienteGlobal.getCorreoElectronico());
        System.out.println(MetodosGenerales.clienteGlobal.isEstado());
        Terminos.dispose();
        Terminos = null;
        WizardPaso0 wizard0 = new WizardPaso0();
        wizard0.setVisible(true);
    }//GEN-LAST:event_btnFinalizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WizardHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WizardHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WizardHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WizardHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new WizardHotel().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Terminos;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JButton btnSugerencias;
    private javax.swing.JComboBox cbxNombresHotel;
    private javax.swing.JComboBox cbxUrlsHotel;
    private javax.swing.JCheckBox chkAcepto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea terminosDeUso;
    private javax.swing.JTextField txtNombreHotel;
    private javax.swing.JTextField txtUrl;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
