/*
 * To change this template, choose Tools | Templates and open the template in
 * the editor.
 */
package vista.wizard;

import controladores.ControladorHotel;
import java.util.List;
import javax.swing.JOptionPane;
import modelos.Habitacion;
import modelos.TipoHabitacion;
import vista.Calendario;

/**
 *
 * @author Pc
 */
public class WizardPaso3 extends javax.swing.JFrame {

    /**
     * Creates new form WizardPaso1
     */
    public static boolean termino;
    
    public WizardPaso3() {
        initComponents();
        setTitle("Definir precios");
        setLocationRelativeTo(null);
       
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnDefinir = new javax.swing.JButton();
        btnFinalizar = new javax.swing.JButton();
        btnMonedas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("PASO 2: Definir precios");

        jLabel2.setText("Asigna precios a cada tipo de habitacion. Puedes configurar hasta tres monedas.");

        btnDefinir.setText("Definir Precios >");
        btnDefinir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDefinirActionPerformed(evt);
            }
        });

        btnFinalizar.setText("Finalizar");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        btnMonedas.setText("+ Monedas >");
        btnMonedas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMonedasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(227, 227, 227)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnMonedas)
                                    .addComponent(btnDefinir))))
                        .addGap(0, 76, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnFinalizar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btnMonedas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDefinir)
                .addGap(18, 18, 18)
                .addComponent(btnFinalizar)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDefinirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDefinirActionPerformed
        // 
        if (!ControladorHotel.monedas.isEmpty()) {
            definir = new TablaDefinirPrecios();
            definir.setLocationRelativeTo(null);
            definir.setVisible(true);
        } else {
            moneda = new DefinirMonedas();
            moneda.setLocationRelativeTo(null);
            moneda.setVisible(true);
        }

    }//GEN-LAST:event_btnDefinirActionPerformed

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        
        if (termino) {
            List<Habitacion> habitacion = ControladorHotel.habitaciones;
            for (Habitacion habitacion1 : habitacion) {
                if (habitacion1.getTipoHabitacion().getMoneda() == null || 
                        habitacion1.getTipoHabitacion().getPrecio()==0.0) {
                    JOptionPane.showMessageDialog(this, "Ud debe definir los precios de los tipos de habitaciones que esta usando.", "Error ingreso de Datos", 2);
                    definir = new TablaDefinirPrecios();
                    definir.setLocationRelativeTo(null);
                    definir.setVisible(true);
                    break;
                } else {
                    Calendario cal = new Calendario();
                    cal.setLocationRelativeTo(null);
                    cal.setVisible(true);
                    this.dispose();
                    break;
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Debe definir todos los precios", "Error ingreso de Datos", 2);
        }

    }//GEN-LAST:event_btnFinalizarActionPerformed

    private void btnMonedasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMonedasActionPerformed
        moneda = new DefinirMonedas();
        moneda.setLocationRelativeTo(null);
        moneda.setVisible(true);
    }//GEN-LAST:event_btnMonedasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WizardPaso3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WizardPaso3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WizardPaso3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WizardPaso3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new WizardPaso3().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDefinir;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JButton btnMonedas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
    private DefinirMonedas moneda;
    private TablaDefinirPrecios definir;
}
